# Variables used by Ansible playbook conf-helloworld.yml

server_name: dockers.nginx.lb 
proxy_pass: http://localhost:8080 
nginx_dir: /etc/nginx/conf.d 
user_dir: /home/ec2-user/docker_repo 
docker_dir: IOMentum-deployment/docker-helloworld-http
repo_github: https://github.com/Demgien/donow_ansible.git